# HW01 — NumPy basics

In [1]:
# Импорт NumPy
import numpy as np

## Создание массивов

In [2]:
# Массив из обычного списка
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [3]:
# Массив из zeros
z = np.zeros((2, 3))
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
# Массив с arange
b = np.arange(0, 10, 2)
b

array([0, 2, 4, 6, 8])

## Атрибуты массива

In [10]:

a.shape, a.dtype

((4,), dtype('int32'))

## Индексация и срезы

In [6]:
# Один элемент
elem = b[2]
elem

4

In [7]:
# Срез подмассива
sub = b[1:4]
sub

array([2, 4, 6])

## Векторные операции

In [8]:
# Поэлементное сложение
c = a[:4] + np.array([10, 10, 10, 10])
c

array([11, 12, 13, 14])

In [9]:
# Среднее значение массива
mean_val = a.mean()
mean_val

2.5